name: 打包 RYFN 外掛
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 壓縮成 mcpack
        run: zip -r RYFN_Ultimate.mcpack . -x ".git*" ".github*"
      - name: 上傳成品
        uses: actions/upload-artifact@v4
        with:
          name: RYFN-成品下載
          path: RYFN_Ultimate.mcpack
